[package]
name = "sigstore_protobuf_specs"
version = "0.1.0-rc.2"
exclude = ["codegen/"]
authors = ["Sigstore Authors <sigstore-dev@googlegroups.com>"]
edition = "2021"
homepage = "https://github.com/sigstore/protobuf-specs"
repository = "https://github.com/sigstore/protobuf-specs"
description = "A library for serializing and deserializing Sigstore messages"
readme = "README.md"
license-file = "LICENSE"
keywords = ["sigstore"]
categories = ["encoding", "parser-implementations"]

[dependencies]
schemafy = "0.6"
schemafy_core = "0.6"
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
pretty_assertions = "1.4.0"