[package]
name = "sigstore_protobuf_specs"
version = "0.3.8"
authors = ["Sigstore Authors <sigstore-dev@googlegroups.com>"]
edition = "2021"
homepage = "https://github.com/sigstore/protobuf-specs"
repository = "https://github.com/sigstore/protobuf-specs"
description = "A library for serializing and deserializing Sigstore messages"
readme = "../README.md"
license = "Apache-2.0"
keywords = ["sigstore"]
categories = ["encoding", "parser-implementations"]

[dependencies]
prost-types = "0.13.4"
prost = "0.13.4"
prost-reflect = { version = "0.14.4", features = ["serde", "derive"] }
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
sigstore-protobuf-specs-derive = { version = "0.0.1", path = "../sigstore-protobuf-specs-derive" }

[build-dependencies]
anyhow = "1.0.72"
glob = "0.3"
prost-build = "0.13.4"
prost-reflect-build = "0.14.0"
which = "7.0.1"
